services:
  - type: web
    name: sceg-details-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3000

  - type: static
    name: sceg-details-frontend
    env: static
    buildCommand: cd frontend && npm install
    staticPublishPath: frontend
    envVars:
      - key: REACT_APP_API_URL
        value: https://sceg-details-backend.onrender.com 