services:
  - type: web
    name: sceg-details-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3000
      - key: FRONTEND_URL
        value: https://stableconsultingengineers.github.io/SCEGDetails
    healthCheckPath: /health
    autoDeploy: true 